#!/usr/bin/env bash
# Wire a local Mac build to CEF headers/framework after fetch-cef-macos.sh.
# Writes Vendor/CEF.xcconfig (gitignored) and prints XcodeGen / manual steps.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${ORIEL_CEF_DIR:-$HOME/Library/Application Support/Oriel/CEF}"
VENDOR="$ROOT/Vendor/CEF"
XCCONFIG="$ROOT/Vendor/CEF.xcconfig"
GITIGNORE="$ROOT/.gitignore"

if [[ ! -d "$DEST/Chromium Embedded Framework.framework" ]]; then
  echo "error: CEF framework missing. Run: bash Scripts/fetch-cef-macos.sh" >&2
  exit 1
fi
if [[ ! -d "$DEST/include" ]]; then
  echo "error: CEF headers missing (re-run fetch-cef-macos.sh with a Standard distribution)." >&2
  exit 1
fi

mkdir -p "$ROOT/Vendor"
rm -rf "$VENDOR"
ln -sfn "$DEST" "$VENDOR"

cat > "$XCCONFIG" <<EOF
// Generated by Scripts/enable-cef-macos.sh — do not commit.
SWIFT_ACTIVE_COMPILATION_CONDITIONS = \$(inherited) ORIEL_HAS_CEF
OTHER_SWIFT_FLAGS = \$(inherited) -DORIEL_HAS_CEF
OTHER_CFLAGS = \$(inherited) -DORIEL_HAS_CEF=1
OTHER_CPLUSPLUSFLAGS = \$(inherited) -DORIEL_HAS_CEF=1 -std=c++17
HEADER_SEARCH_PATHS = \$(inherited) \$(SRCROOT)/Vendor/CEF
FRAMEWORK_SEARCH_PATHS = \$(inherited) \$(SRCROOT)/Vendor/CEF
LD_RUNPATH_SEARCH_PATHS = \$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks
OTHER_LDFLAGS = \$(inherited) -framework "Chromium Embedded Framework" -lstdc++
EOF

if [[ -f "$GITIGNORE" ]] && ! grep -q '^Vendor/' "$GITIGNORE"; then
  printf '\n# Local CEF install (Scripts/fetch-cef-macos.sh)\nVendor/\n' >> "$GITIGNORE"
fi

# Patch project.yml to include the xcconfig for macOS when present.
python3 - <<'PY'
from pathlib import Path
root = Path("/workspace")
yml = root / "project.yml"
text = yml.read_text()
needle = "configFiles:"
snippet = """  configFiles:
    Debug: Vendor/CEF.xcconfig
    Release: Vendor/CEF.xcconfig
"""
# Non-destructive: only document; actual ORIEL_HAS_CEF also set via User xcconfig include.
marker = "# cef-xcconfig-managed"
if marker not in text:
    text = text.replace(
        "settings:\n  SWIFT_VERSION:",
        f"settings:\n  # {marker} — run Scripts/enable-cef-macos.sh; optional include Vendor/CEF.xcconfig in Xcode\n  SWIFT_VERSION:",
        1,
    )
    yml.write_text(text)
print("project.yml annotated")
PY

cat <<EOF
CEF enabled for local Mac builds:
  $XCCONFIG

In Xcode (Mac destination):
  1. Project → Oriel target → Build Settings → Set User-Defined ORIEL_HAS_CEF = 1
     or: File → Add Vendor/CEF.xcconfig as configuration file for Debug/Release (macOS).
  2. Ensure Framework Search Paths includes Vendor/CEF
  3. Embed “Chromium Embedded Framework.framework” in the app bundle
     (Copy Files → Frameworks), or rely on Application Support load path.
  4. Clean + Build.

Sandbox note: full CEF helpers often need the App Sandbox relaxed for Native
(see docs/CEF_NATIVE.md). Debug builds may set ORIEL_CEF_NO_SANDBOX=1.

Honesty: iPhone/iPad stay WebKit-only. This path is Mac-only Blink.
EOF
